// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7BLmMpP6-8V-pkV_Xs61HcnYx10GxEC4',
    appId: '1:254716694165:web:f2d78e111bd851017ed59c',
    messagingSenderId: '254716694165',
    projectId: 'cmsc23-todo-app-arcastillo1',
    authDomain: 'cmsc23-todo-app-arcastillo1.firebaseapp.com',
    storageBucket: 'cmsc23-todo-app-arcastillo1.appspot.com',
    measurementId: 'G-11SZFFTB6B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwqagEQXitF_0bbHiEotNWYWhYR7EgsC0',
    appId: '1:254716694165:android:35b2ad8081f8f4067ed59c',
    messagingSenderId: '254716694165',
    projectId: 'cmsc23-todo-app-arcastillo1',
    storageBucket: 'cmsc23-todo-app-arcastillo1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB91F1Zaw1E1qVOWIUMybOyQoiETkeoR1E',
    appId: '1:254716694165:ios:b1223e13351a165c7ed59c',
    messagingSenderId: '254716694165',
    projectId: 'cmsc23-todo-app-arcastillo1',
    storageBucket: 'cmsc23-todo-app-arcastillo1.appspot.com',
    iosClientId: '254716694165-8d2adspqhd006b1qjrbjish7s0fojv0q.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB91F1Zaw1E1qVOWIUMybOyQoiETkeoR1E',
    appId: '1:254716694165:ios:b1223e13351a165c7ed59c',
    messagingSenderId: '254716694165',
    projectId: 'cmsc23-todo-app-arcastillo1',
    storageBucket: 'cmsc23-todo-app-arcastillo1.appspot.com',
    iosClientId: '254716694165-8d2adspqhd006b1qjrbjish7s0fojv0q.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );
}
